version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: oops
    ports:
      - "3306:3306"
    networks:
      - redis-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis
    container_name: redis-server
    restart: always
    networks:
      - redis-net
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # MySQL이 완전히 실행될 때까지 기다림
      redis:
        condition: service_started
    networks:
      - redis-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/oops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    ports:
      - "8080:8080"

networks:
  redis-net:
    driver: bridge
