spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://todaycoinfo.com/login/oauth2/code/google
            scope:
              - profile
              - email
      authorization-server:
        base-uri: https://todaycoinfo.com