spring:
  application:
    name: oops
---
spring:
  profiles:
    include: oauth
---
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/oops #로컬 mysql
    #url: jdbc:mysql://10.0.3.37:3306/oops   #docker container mysql
    url: jdbc:mysql://${RDS_HOST}:3306/oops?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    #username: root
    #password: mysql
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      #host: localhost  # 로컬 Docker 네트워크 내 컨테이너 이름 사용
      #host: 10.0.6.114   # 레디스 서버 분리
      host: redis-service.default.svc.cluster.local  # 쿠버네티스 DNS - default
      port: 6379
---
server:
  servlet:
    session:
      cookie:
        domain: todaycoinfo.com
        name: JSESSIONID
        secure: true             # HTTPS에서만 전송
        http-only: true          # JS 접근 금지
        same-site: None          # 다른 도메인으로도 전송 허용
  port: 8080
  cors:
    allowed-origins:
      - "http://localhost"
      - "https://d3pdkkr961vb7.cloudfront.net"
      - "https://todaycoinfo.com"
      - "https://api.todaycoinfo.com"
      - "http://todaycoinfo.com"
      - "http://api.todaycoinfo.com"
---
spring:
  websocket:
    enabled: true
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL_USERNAME}
    password: ${GOOGLE_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          ssl:
            trust: smtp.gmail.com  # SSL 인증 문제 방지
---
logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG